In [1]:
import io
import pandas as pd
from google.colab import files

In [2]:
df = pd.read_excel('/content/Internship Task_1 (3).xlsx')

In [3]:
df.head(30)

,Company Name,INDUSTRY,PHONE NUMBER,BUSINESS VERTICLE,ABOUT US,COMPANY FORMED,TURNOVER,WEBSITE,EMAIL,Unnamed: 9,LATEST ACCOUNTS,Unnamed: 11,Unnamed: 12,Unnamed: 13,FX Arises
0,OPALION PLASTICS LIMITED.,Wholesale And Retail Trade; Repair Of Motor Ve...,NaN,Non-specialised wholesale trade,NaN,"40 years, 10 months",Â£14.0m,NaN,NaN,NaN,NaN,NaN,NaN,NaN,... ACCOUNTING POLICIES - continued Foreign cu...
1,GREENWICH FLOORING LIMITED,Real Estate Activities,NaN,Real estate agencies,NaN,"8 years, 4 months",Â£1.09m,NaN,NaN,NaN,NaN,NaN,NaN,NaN,... of the state of affairs of the company as ...
2,ULTRAMEDIC (HOLDINGS) LIMITED,Administrative And Support Service Activities,0151 228 0354,Other business support service activities n.e.c.,Fluke biomedical test equipment UK: Ultramedic...,"7 years, 7 months",Â£4.73m,https://ultramedic.com/,sales@ultramedic.com,NaN,NaN,NaN,NaN,NaN,... required to show a true and fair view. The...
3,MES (HOLDINGS) LIMITED,Real Estate Activities,#ERROR!,Letting and operating of own or leased real es...,Marine Electronic Systems is a leading systems...,"8 years, 3 months",Â£4.49m,http://www.mesuk.com/p/home.html,sales@mesuk.com,NaN,NaN,NaN,NaN,NaN,... required to show a true and fair view. The...
4,BELLERIVE FINANCE LIMITED,Financial And Insurance Activities,#ERROR!,Other credit granting (not including credit gr...,Bellerive is dedicated to seeing our clients a...,"33 years, 4 months",Â£2.59m,https://bellerivefinance.com/,info@bellerivefinance.com,NaN,NaN,NaN,NaN,NaN,... that they give a true and fair view of the...
5,CERILLION PLC,Information And Communication,#ERROR!,Other telecommunications activities,Cerillion plc is a leading provider of billing...,"7 years, 2 months",Â£26.1m,https://www.cerillion.com/,info@cerillion.com,NaN,"Has Office overseas, Fast growth >20% YoY, Has...",NaN,NaN,NaN,... keep pace with the changing market The Gro...
6,EXQUISITE GAMING LIMITED,Wholesale And Retail Trade; Repair Of Motor Ve...,NaN,Wholesale of household goods (other than music...,NaN,"8 years, 3 months",Â£13.4m,NaN,NaN,NaN,NaN,NaN,NaN,NaN,... contract is entered into and are subsequen...
7,T.S.L. ELECTRICAL AND DATA SERVICES LTD,Construction,#ERROR!,Electrical installation,TSL Electrical Data Services Ltd have been est...,"15 years, 8 months",Â£1.74m,https://www.tsl-services.co.uk/,sales@tsl-services.co.uk,NaN,NaN,NaN,NaN,NaN,... required to show a true and fair view. The...
8,QVIS LIGHTING & SECURITY LIMITED,Manufacturing,NaN,Manufacture of electric lighting equipment,NaN,"8 years, 3 months",Â£17.1m,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"... risk assessment, our procedures incl uded,..."
9,OPEN 24 SEVEN LIMITED,Wholesale And Retail Trade; Repair Of Motor Ve...,0117 325 2470,Other retail sale of new goods in specialised ...,"SpyCameraCCTV offers a range of CCTV cameras, ...","14 years, 10 months",Â£1.65m,https://www.spycameracctv.com/,sales@spycameracctv.com,NaN,NaN,NaN,NaN,NaN,... The accounts have been prepared under the ...
10,BELLEZO.COM LTD,Wholesale And Retail Trade; Repair Of Motor Ve...,0844 870 7376,Retail sale of cosmetic and toilet articles in...,"bellezo.com, beauty - enhanced by service. Off...","11 years, 4 months",Â£17.9m,NaN,info@bellezo.com,NaN,NaN,NaN,NaN,NaN,... statements have been prepared under the hi...
11,ULTROMEX LTD,Manufacturing,0151 203 8377,Manufacture of machinery for metallurgy,Salt slag recycling | salt cake recycling. SAL...,"10 years, 11 months",Â£6.62m,https://www.ultromex.com/,sales@ultromex.com,NaN,"Manufacturing , Cash Rich >Â£1m, Has LEI Number...",NaN,NaN,NaN,... required to show a true and fair view. The...
12,BELLFORGE CAPITAL PARTNERS LIMITED,"Professional, Scientific And Technical Activities",NaN,Activities of head offices,See relevant content for Dore.co.uk,"13 years, 7 months",Â£1.37m,http://parked.dore.co.uk/,NaN,NaN,NaN,NaN,NaN,NaN,... of the state of affairs of the company as ...
13,SENSATIONS INTERNATIONAL LIMITED,Administrative And Support Service Activities,NaN,Other business support service activities n.e.c.,We use cookies to design our website optimally...,"24 years, 3 months",Â£1.80m,http://sensationscards.co.uk/defaultsite,NaN,NaN,NaN,NaN,NaN,NaN,... other future taxable profits. Foreign curr...
14,T.W. WARD C.N.C. MACHINERY LIMITED,Manufacturing,0114 276 5411,Installation of industrial machinery and equip...,T W Ward CNC Machinery Ltd is one of the UKâ€™s ...,"38 years, 7 months",Â£9.44m,https://www.wardcnc.com/,sales@wardcnc.com,NaN,"Manufacturing , Has LEI Number, Has Imp/Exp re...",NaN,NaN,NaN,"... overdraft and a bank loan, the main purpos..."
15,"T.WARD & SON,LIMITED",Wholesale And Retail Trade; Repair Of Motor Ve...,01229 811222,"Retail sale of hardware, paints and glass in s...","Wardgroup Plumbers, Double Glazing Installers,...","94 years, 10 months",Â£3.35m,https://wardgroup.co.uk/,enquiries@wardgroup.co.uk,NaN,NaN,NaN,NaN,NaN,... of the state of affairs of the company as ...
16,T.WHITWELL & SONS LIMITED,"Agriculture, Forestry And Fishing",NaN,Raising of dairy cattle,NaN,"62 years, 11 months",Â£2.43m,NaN,NaN,NaN,NaN,NaN,NaN,NaN,... of the state of affairs of the company as ...
17,OPEN DESTINATIONS LIMITED,Information And Communication,#ERROR!,Other information technology and computer serv...,Open Destinations is a specialist in travel te...,"24 years, 1 month",Â£6.85m,https://www.opendestinations.com/,NaN,NaN,"Cash Rich >Â£1m, Raised Investment, Has LEI Num...",NaN,NaN,NaN,... company was also able to win new customers...
18,BELLIS BROTHERS LIMITED,Wholesale And Retail Trade; Repair Of Motor Ve...,01829 270304,Retail sale of fruit and vegetables in special...,Independently run family business located less...,"113 years, 6 months",Â£31.0m,https://www.bellisbrothers.co.uk/,info@bellisbrothers.co.uk,NaN,"Wholesale/Retail, Cash Rich >Â£1m, Has LEI Number",NaN,NaN,NaN,... payable on equity instruments are recognis...
19,MESSENGER'S FRENCH POLISHING LIMITED,Construction,NaN,Other building completion and finishing,NaN,"5 years, 10 months",Â£1.06m,NaN,NaN,NaN,NaN,NaN,NaN,NaN,... small entities by section 1A of the standa...
20,IP-PERFORMANCE LTD,Information And Communication,01275 393 382,Other information technology and computer serv...,"Web, cloud and network security, technical sup...","27 years, 7 months",Â£1.55m,https://www.ip-performance.co.uk/,marketing@ip-performance.co.uk,NaN,NaN,NaN,NaN,NaN,... Accounting policies 1.4 Tangible fixed ass...
21,LAW FINANCIAL PLANNING LIMITED,Financial And Insurance Activities,01603 763875,Life insurance,Professional firm of Independent Financial Adv...,"24 years, 0 months",Â£2.31m,https://www.lawfinancialplanning.co.uk/,NaN,NaN,NaN,NaN,NaN,NaN,... of the state of affairs of the company as ...
22,EXTRA (UK) LIMITED,Wholesale And Retail Trade; Repair Of Motor Ve...,NaN,Non-specialised wholesale trade,NaN,"27 years, 5 months",Â£24.5m,https://extrauk.co.uk/,NaN,NaN,NaN,NaN,NaN,NaN,... that they give a true and fair view of the...
23,R & B PHARMA LTD.,Wholesale And Retail Trade; Repair Of Motor Ve...,NaN,Dispensing chemist in specialised stores,NaN,"12 years, 10 months",Â£1.12m,NaN,NaN,NaN,NaN,NaN,NaN,NaN,... 20 years If there is an indication that th...
24,T5 PRODUCT DISTRIBUTION LIMITED,Administrative And Support Service Activities,#ERROR!,Other business support service activities n.e.c.,General Paint UK Supplying the automotive refi...,"13 years, 3 months",Â£1.40m,https://www.generalpaintuk.co.uk/,info@generalpaintuk.co.uk,NaN,NaN,NaN,NaN,NaN,... Its registered office is: Unit 2 Blair Way...
25,IPE VENTURES LIMITED,Financial And Insurance Activities,NaN,Activities of venture and development capital ...,NaN,"5 years, 4 months",Â£18.7m,NaN,NaN,NaN,NaN,NaN,NaN,NaN,... and the requirements of the Companies Act ...
26,MET MEDICAL LTD,Human Health And Social Work Activities,0203 627 9042,Other human health activities,Leading Private Ambulance Service based in Her...,"8 years, 3 months",Â£1.19m,https://www.met-medical.co.uk/,bookings@met-medical.co.uk,NaN,NaN,NaN,NaN,NaN,... â€˜The Financial Reporting Standard applicab...
27,MET TRADERS LIMITED,Financial And Insurance Activities,020 7604 5777,Security dealing on own account,Forget sitting on the sidelines and watching o...,"19 years, 7 months",Â£5.81m,http://mettraders.com/,info@themetgroup.com,NaN,"Raised Investment, Has LEI Number, FX in Accou...",NaN,NaN,NaN,... TRADERS LIMITED NOTES TO THE FINANCIAL STA...
28,OPEN SOURCE CAPITAL LIMITED,Financial And Insurance Activities,NaN,Activities of financial services holding compa...,NaN,"5 years, 3 months",Â£2.57m,NaN,NaN,NaN,NaN,NaN,NaN,NaN,... required to show a true and fair view. The...
29,SENTINEL FINANCE LIMITED,Financial And Insurance Activities,NaN,Security dealing on own account,NaN,"7 years, 0 months",Â£4.25m,NaN,NaN,NaN,NaN,NaN,NaN,NaN,... of the state of affairs of the company as ...

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Company Name       1000 non-null   object
 1   INDUSTRY           1000 non-null   object
 2   PHONE NUMBER       593 non-null    object
 3   BUSINESS VERTICLE  1000 non-null   object
 4   ABOUT US           657 non-null    object
 5   COMPANY FORMED     1000 non-null   object
 6   TURNOVER           1000 non-null   object
 7   WEBSITE            640 non-null    object
 8   EMAIL              506 non-null    object
 9   Unnamed: 9         0 non-null      float64
 10  LATEST ACCOUNTS    280 non-null    object
 11  Unnamed: 11        7 non-null      object
 12  Unnamed: 12        7 non-null      object
 13  Unnamed: 13        0 non-null      float64
 14  FX Arises          1000 non-null   object
dtypes: float64(2), object(13)
memory usage: 117.3+ KB

In [5]:
print('Data Shape:',df.shape)
print('Data Size:',df.size)

Data Shape: (1000, 15)
Data Size: 15000

In [6]:
#checking for null values
df.isnull().any()

Company Name         False
INDUSTRY             False
PHONE NUMBER          True
BUSINESS VERTICLE    False
ABOUT US              True
COMPANY FORMED       False
TURNOVER             False
WEBSITE               True
EMAIL                 True
Unnamed: 9            True
LATEST ACCOUNTS       True
Unnamed: 11           True
Unnamed: 12           True
Unnamed: 13           True
FX Arises            False
dtype: bool

In [7]:
#checking for Nan value
df.isna().any()

Company Name         False
INDUSTRY             False
PHONE NUMBER          True
BUSINESS VERTICLE    False
ABOUT US              True
COMPANY FORMED       False
TURNOVER             False
WEBSITE               True
EMAIL                 True
Unnamed: 9            True
LATEST ACCOUNTS       True
Unnamed: 11           True
Unnamed: 12           True
Unnamed: 13           True
FX Arises            False
dtype: bool

In [8]:
df.skew()

<ipython-input-8-9e0b1e29546f>:1: FutureWarning: The default value of numeric_only in DataFrame.skew is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.skew()

Unnamed: 9    NaN
Unnamed: 13   NaN
dtype: float64

In [9]:
df.fillna('Not Available', inplace=True)
df['PHONE NUMBER']=df['PHONE NUMBER'].replace('#ERROR!','Not Available')

In [10]:
#Drop the duplicates
df.drop_duplicates()

,Company Name,INDUSTRY,PHONE NUMBER,BUSINESS VERTICLE,ABOUT US,COMPANY FORMED,TURNOVER,WEBSITE,EMAIL,Unnamed: 9,LATEST ACCOUNTS,Unnamed: 11,Unnamed: 12,Unnamed: 13,FX Arises
0,OPALION PLASTICS LIMITED.,Wholesale And Retail Trade; Repair Of Motor Ve...,Not Available,Non-specialised wholesale trade,Not Available,"40 years, 10 months",Â£14.0m,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,... ACCOUNTING POLICIES - continued Foreign cu...
1,GREENWICH FLOORING LIMITED,Real Estate Activities,Not Available,Real estate agencies,Not Available,"8 years, 4 months",Â£1.09m,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,... of the state of affairs of the company as ...
2,ULTRAMEDIC (HOLDINGS) LIMITED,Administrative And Support Service Activities,0151 228 0354,Other business support service activities n.e.c.,Fluke biomedical test equipment UK: Ultramedic...,"7 years, 7 months",Â£4.73m,https://ultramedic.com/,sales@ultramedic.com,Not Available,Not Available,Not Available,Not Available,Not Available,... required to show a true and fair view. The...
3,MES (HOLDINGS) LIMITED,Real Estate Activities,Not Available,Letting and operating of own or leased real es...,Marine Electronic Systems is a leading systems...,"8 years, 3 months",Â£4.49m,http://www.mesuk.com/p/home.html,sales@mesuk.com,Not Available,Not Available,Not Available,Not Available,Not Available,... required to show a true and fair view. The...
4,BELLERIVE FINANCE LIMITED,Financial And Insurance Activities,Not Available,Other credit granting (not including credit gr...,Bellerive is dedicated to seeing our clients a...,"33 years, 4 months",Â£2.59m,https://bellerivefinance.com/,info@bellerivefinance.com,Not Available,Not Available,Not Available,Not Available,Not Available,... that they give a true and fair view of the...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,ANCHOR DOOR SYSTEMS LIMITED,Administrative And Support Service Activities,020 7582 6598,Combined facilities support activities,Anchor Door Systems is accredited by SafeContr...,"35 years, 3 months",Â£2.48m,https://anchorgroup.co.uk/,helpdesk@anchorgroup.co.uk,Not Available,Not Available,Not Available,Not Available,Not Available,... The accounts have been prepared under the ...
996,CLEAR CUT PICTURES LIMITED,Information And Communication,Not Available,"Motion picture, video and television programme...",Clear Cut are renowned for providing highly cr...,"28 years, 11 months",Â£2.02m,https://www.clearcut.cc/,sales@clearcut.cc,Not Available,Not Available,Not Available,Not Available,Not Available,... of the state of affairs of the company as ...
997,RELCROSS LIMITED,Wholesale And Retail Trade; Repair Of Motor Ve...,01380 729600,Non-specialised wholesale trade,relcross door controlsÂ® | We distribute LCN Cl...,"21 years, 4 months",Â£1.65m,https://www.relcross.co.uk/,sales@relcross.co.uk,Not Available,Not Available,Not Available,Not Available,Not Available,... Fixtures and fittings Other computer equip...
998,ANCHOR MAGNETS LIMITED,Manufacturing,Not Available,Other manufacturing n.e.c.,Not Available,"8 years, 10 months",Â£4.18m,https://www.anchormagnetsonline.com/,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,... is required to show a true and fair view T...
999,CLEAR FINANCIAL ADVICE LIMITED,Financial And Insurance Activities,020 8669 3828,"Other financial service activities, except ins...",For over 30 years as professional independent ...,"20 years, 5 months",Â£1.41m,https://clearfinancialadvice.co.uk/,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,... of the state of affairs of the company as ...

In [11]:
# df = df.dropna(subset=['WEBSITE','Unnamed: 9','Unnamed: 11','Unnamed: 12','Unnamed: 13'])
df['OVERSEAS']=False

In [12]:
# df = df[df['LATEST ACCOUNTS'].str.contains('Overseas','Has Imp/Exp','International','Brexit')]

In [13]:
df1 = df[df['LATEST ACCOUNTS'].str.contains('Overseas','Has Imp/Exp')]

In [14]:
df_c_name = df['Company Name']
df1_c_name = df1['Company Name']

df.loc[df_c_name.isin(df1_c_name), 'OVERSEAS'] = True

In [15]:
df['TURNOVER'].replace('Â£','',regex=True,inplace=True)
df['TURNOVER'].replace('m','',regex=True,inplace=True)
df['TURNOVER'] = df['TURNOVER'].astype(float)

In [16]:
import numpy as np

df = df.assign(unit=lambda df: df["COMPANY FORMED"].str.extract("([a-z]+)+"),
         val=lambda df: df["COMPANY FORMED"].str.extract("([0-9,\.]+)").astype(float),
         months=lambda df: np.where(df["unit"].isin(["month","months"]), df["val"],
                                    np.where(df["unit"].isin(["year","years"])
                                             &df["val"].lt(55), df["val"]*12, np.nan)))

In [17]:
# df = df.data[df['OVERSEAS']==True].rank(ascending=True)
# df['Rank'] = df.groupby('months')['OVERSEAS'].rank(ascending=False)
# df = df.drop('Rank', axis=1)

df.sort_values(by=['OVERSEAS', 'TURNOVER','val'],ascending=[False,False,False])


# col1 = df["SaleCount"].astype(str)
# col2 = df["TotalRevenue"].astype(str)
# df['Rank'] = (col1+col2).astype(int).rank(method='dense', ascending=False).astype(int)
# df.sort_values('Rank')

,Company Name,INDUSTRY,PHONE NUMBER,BUSINESS VERTICLE,ABOUT US,COMPANY FORMED,TURNOVER,WEBSITE,EMAIL,Unnamed: 9,LATEST ACCOUNTS,Unnamed: 11,Unnamed: 12,Unnamed: 13,FX Arises,OVERSEAS,unit,val,months
986,ANAND INTERNATIONAL LIMITED,Wholesale And Retail Trade; Repair Of Motor Ve...,0116 282 3900,"Wholesale of gramophone records, audio tapes, ...",Anand is Europeâ€™s leading brand management com...,"41 years, 0 months",46.90,https://anand.co.uk/,sales@anand.co.uk,Not Available,"Wholesale/Retail, ""International"" on website, ...",Not Available,Not Available,Not Available,... economic benefit will be transferred to se...,True,years,41.0,492.0
817,THE ALAN NUTTALL PARTNERSHIP LIMITED,Manufacturing,Not Available,Manufacture of other fabricated metal products...,Nuttall is one of the UKâ€™s foremost store fitt...,"47 years, 6 months",43.20,https://www.thealannuttallpartnership.co.uk,info@tanp.co.uk,Not Available,"Manufacturing , ""International"" on website, Ha...",Not Available,Not Available,Not Available,THE ALAN NUTTALL PARTNERSHIP LIMITED (REGISTER...,True,years,47.0,564.0
126,MGF LIMITED,"Professional, Scientific And Technical Activities",0845 485 3771,Activities of head offices,MGF deliver comprehensive temporary works solu...,"21 years, 3 months",40.90,https://mgf.co.uk/,enquiries@mgf.co.uk,Not Available,"Cash Rich >Â£1m, Has LEI Number, Exp/Imp in New...",Not Available,Not Available,Not Available,... a true and fair view of the state of affai...,True,years,21.0,252.0
229,TARGET COMPONENTS LIMITED,Wholesale And Retail Trade; Repair Of Motor Ve...,01977 739 300,"Wholesale of computers, computer peripheral eq...",Hello Guest Welcome to Target Components The U...,"26 years, 7 months",39.80,https://www.targetcomponents.co.uk/,sales@targetcomponents.co.uk,Not Available,"Wholesale/Retail, Cash Rich >Â£1m, Has LEI Numb...",Not Available,Not Available,Not Available,... obtain reasonable assurance about whether ...,True,years,26.0,312.0
130,LEA REDWAY LIMITED,"Professional, Scientific And Technical Activities",Not Available,Activities of head offices,Albright wholly designs and manufactures our o...,"79 years, 2 months",38.70,https://www.albrightinternational.com/,info@sevtronic.com,Not Available,"Has Office overseas, Cash Rich >Â£1m, Has LEI N...",Not Available,Not Available,Not Available,... the directors' use of the going concern ba...,True,years,79.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40,GRESHAM WEALTH MANAGEMENT (FS) LIMITED,"Professional, Scientific And Technical Activities",0161 973 9150,Financial management,"Chartered financial planners, Gresham Wealth M...","8 years, 2 months",1.02,https://www.greshamwm.co.uk/,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,... of the cash-generating units that are expe...,False,years,8.0,96.0
693,MJC2 LIMITED,Information And Communication,Not Available,Business and domestic software development,"Advanced, flexible planning and scheduling sof...","31 years, 9 months",1.01,https://www.mjc2.com/,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,... YEAR ENDED 31 AUGUST 2021 (CONTINUED) 2 Ac...,False,years,31.0,372.0
945,THE CEDARS NURSERY LIMITED,Education,0191 565 2549,Pre-primary education,"The North East's Cedars Nursery, Ofsted Outsta...","25 years, 8 months",1.01,https://www.cedarsnursery.co.uk/,newcastle@cedarsnursery.co.uk,Not Available,Not Available,Not Available,Not Available,Not Available,... properties measured at fair value through ...,False,years,25.0,300.0
876,FISHERS' (CROUCH END) LIMITED,Real Estate Activities,Not Available,Letting and operating of own or leased real es...,Not Available,"79 years, 9 months",1.00,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,... properties measured at fair value through ...,False,years,79.0,NaN
532,SHORE HALL ESTATE LIMITED,"Agriculture, Forestry And Fishing",Not Available,"Growing of cereals (except rice), leguminous c...",Not Available,"65 years, 1 month",1.00,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,... payable on equity instruments are recognis...,False,years,65.0,NaN

In [18]:
import numpy as np
import pandas as pd

## Get All company Links
import requests
from bs4 import BeautifulSoup

In [19]:
from sqlalchemy.sql.expression import null
CompanyID = []
for index, i in df.iterrows():
    # print(i['Company Name'])
    # if index>=100: #continue to start loop from second value
    #     continue
    req = requests.get('https://find-and-update.company-information.service.gov.uk/search?q='+ str(i['Company Name'])).text
    soup = BeautifulSoup(req, 'html.parser')
    link = soup.find(['h3', 'a'], class_='govuk-link',title='View company')
    cid = link.get('href') if link else ''
    CompanyID.append(cid)

    # if df['Company Name'].value[index] == link.get_text():
        # print(link.get('href'))
    # df['CompanyId'].values[index]=link.get("a")

In [20]:
# CompanyID= CompanyID.replace(r'\s+|\\n', ' ', regex=True)
df['CompanyId'] =pd.Series(CompanyID)
# CompanyID

In [30]:
from pandas.core.internals.construction import Manager
import re
Managers = []
Links = []
# Roles = []
for index, i in df.iterrows():
    # print(i['Company Name'])
    # if index>=100: #continue to start loop from second value
    #     continue
    # print(i['CompanyId'  ])
    req = requests.get('https://find-and-update.company-information.service.gov.uk/'+ str(i['CompanyId'])+'/officers').text
    soup = BeautifulSoup(req, 'html.parser')
    value=index+1
    # c='appointment-'+va
    # manager = soup.find_all("span", {"id": re.compile("officer-name-")},"a")
    allManager = soup.select('div h2 span a' ,class_="govuk-link")
    # allR = soup.select('div dl.column-quarter dd' , class_="data")
    allManagerName = []
    allManagerLink = []
    # allManagerRole = []
    mr=[]
    for manager in allManager:
      mname = manager.get_text() if manager else ''
      mlink = manager.get('href') if manager else ''
      allManagerName.append(mname+':')
      allManagerLink.append(mlink+':')
    Managers.append(allManagerName)
    Links.append(allManagerLink)
    # for r in allR:
    #   mr = r.get_text() if r else ''
    #   print(mr)
    #   allManagerRole.append(mr)
    # Roles.append(mr)
    # print(len(allManagerLink))
    # print(manager)
    # cid = link.get('href') if link else ''
    # CompanyID.append(cid)

In [31]:
df['Manager'] = pd.Series(Managers)
df['Manager Profile'] = pd.Series(Links)
# df['Role'] = pd.Series(Roles)

In [32]:
final_csv_data = df.to_excel('final.xlsx', index = True)